# Generated by Django 4.1.7 on 2023-03-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='like_count',
            field=models.IntegerField(),
        ),
    ]
